---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r, echo=TRUE}
# Load the data
setwd("~/Desktop")
sports_data <- read.csv("activity.csv", head=TRUE)
```


## What is mean total number of steps taken per day?
```{r, echo=TRUE}
# Calculate the total number of steps taken per day
daily_total_steps <- aggregate(sports_data[, 1], list(sports_data$date), sum)
colnames(daily_total_steps) <- c("date", "daily_total_steps")
daily_total_steps$daily_total_steps

# Make a histogram of the total number of steps taken each day
hist(daily_total_steps$daily_total_steps, 
     main = "Histogram of Total Number of Steps Taken per Day",
     xlab = "Total Number of Steps Daily",
     col="Blue"
     )

# Calculate the mean of the total number of steps taken per day
round(mean(daily_total_steps$daily_total_steps, na.rm = TRUE), 0)

# Calculate the median of the total number of steps taken per day
median(daily_total_steps$daily_total_steps, na.rm = TRUE)
```


## What is the average daily activity pattern?
```{r, echo=TRUE}
# Make a time series plot
stepsMeanPerInterval <- tapply(sports_data$steps, sports_data$interval, 
                               mean, na.rm = T)
summary(stepsMeanPerInterval)
plot(stepsMeanPerInterval, type = "l", 
     main = ("Steps vs. Interval (daily average)"), 
     ylab = "# of steps")

# Which 5-minute interval, on average across all the days in the dataset, 
# contains the maximum number of steps?
seq(along = stepsMeanPerInterval)[stepsMeanPerInterval == max(stepsMeanPerInterval)]
```


## Imputing missing values
```{r, echo=TRUE}
# the total number of rows with NAs
summary(sports_data$steps)[7]

#
# Get the steps mean per interval as a vector
tmp_stepsMeanPerInterval <- as.vector(stepsMeanPerInterval)
# Repeat it to be the same for each of the 61 days
tmp_stepsMeanPerInterval <- rep(tmp_stepsMeanPerInterval, 61)
# Set it one where there is no missin data
tmp_stepsMeanPerInterval[!is.na(sports_data$steps)] = 1

# Get the steps data as a vector
tmp_dataTest <- as.vector(sports_data$steps)
# Set it to one where data is missing
tmp_dataTest[is.na(tmp_dataTest)] = 1

data_NoMissing <- sports_data
data_NoMissing$steps <- tmp_stepsMeanPerInterval * tmp_dataTest

stepsTotalPerDay_NoMissing <- tapply(data_NoMissing$steps, data_NoMissing$date, 
                                     sum)
# Make a new hisogram 
hist(stepsTotalPerDay_NoMissing, breaks = 6, 
     main = "Frequency of number of steps per day", 
     xlab = "Number of steps per day", ylab = "Frequency", col = "blue")

# The spike in the middle of the histogram has increased due to the filling in
# missing value in the dataset

stepsMeanPerInterval_NoMissing <- tapply(data_NoMissing$steps, 
                                         data_NoMissing$interval, mean)

mean(stepsTotalPerDay_NoMissing)
median(stepsTotalPerDay_NoMissing)

plot(stepsMeanPerInterval_NoMissing, type = "l", xlab = "Interval", 
     ylab = "# of Steps", 
     main = "Steps vs. Interval (missing replaced with mean)")
```


## Are there differences in activity patterns between weekdays and weekends?
```{r, echo=TRUE}
# Create a factor variable with two levels (weekday, weekend-day)
tmpLT <- as.POSIXlt(sports_data$date, format = "%Y-%m-%d")
tmpWeekDays <- tmpLT$wday
tmpWeekDays[tmpWeekDays == 0] = 0
tmpWeekDays[tmpWeekDays == 6] = 0
tmpWeekDays[tmpWeekDays != 0] = 1
tmpWeekDaysFactor <- factor(tmpWeekDays, levels = c(0, 1))
# Add the factor variable to the data
sports_data$WD <- tmpWeekDaysFactor
# Calculate the mean
stepsMeanPerWeekday <- tapply(sports_data$steps, 
                              list(sports_data$interval, sports_data$WD), 
                              mean, na.rm = T)

par(mfrow = c(2, 1))
# Display the 2 plots
with(sports_data, {
    par(mai = c(0, 1, 1, 0))
    plot(stepsMeanPerWeekday[, 1], type = "l", main = ("Steps vs. Interval"), 
        xaxt = "n", ylab = "Week ends")
    title = ("# of Steps v.s. Interval")
    par(mai = c(1, 1, 0, 0))
    plot(stepsMeanPerWeekday[, 2], type = "l", xlab = "Interval", ylab = "Week days")

})
```